name: Export my Secrets

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  create-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create secrets file
        run: |
          echo "IA_EMAIL=${{ secrets.IA_EMAIL }}" > secrets.txt
          echo "IA_PASSWORD=${{ secrets.IA_PASSWORD }}" >> secrets.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: secrets-file
          path: secrets.txt
