name: Archive Video to IA

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Git URL to archive'
        required: true
        default: 'https://github.com/'

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-archive-cache-${{ hashFiles('.github/workflows/iagitbetter.yml') }}
        restore-keys: |
          ${{ runner.os }}-archive-cache-

    - name: Install iagitbetter and IA CLI
      run: |
        python -m pip install --upgrade pip
        pip install iagitbetter internetarchive

    - name: Configure IA CLI
      env:
        IA_EMAIL: ${{ secrets.IA_EMAIL }}
        IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
      run: |
        printf "%s\n%s\n" "$IA_EMAIL" "$IA_PASSWORD" | ia configure

    - name: Run iagitbetter
      run: |
        iagitbetter "${{ github.event.inputs.url }}"
